/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAdminResponseDtoFromDiscriminatorValue, createApiProblemDetailsFromDiscriminatorValue, serializeAdminResponseDto, serializeUpdateAdminProfileRequestDto, type AdminResponseDto, type ApiProblemDetails, type UpdateAdminProfileRequestDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /admins/{adminId}
 */
export interface WithAdminItemRequestBuilder extends BaseRequestBuilder<WithAdminItemRequestBuilder> {
    /**
     * Updates administrator name and email. An unchanged profile is a successful no-op. A concurrent change returns 409; an administrator removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdminResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 404 status code
     * @throws {ApiProblemDetails} error when the service returns a 409 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     put(body: UpdateAdminProfileRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdminResponseDto | undefined>;
    /**
     * Updates administrator name and email. An unchanged profile is a successful no-op. A concurrent change returns 409; an administrator removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateAdminProfileRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithAdminItemRequestBuilderUriTemplate = "{+baseurl}/admins/{adminId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithAdminItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithAdminItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdminResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateAdminProfileRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
