/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithClientItemRequestBuilder, WithClientItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /client-data-versions/client
 */
export interface ClientRequestBuilder extends BaseRequestBuilder<ClientRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.clientDataVersions.client.item collection
     * @param clientId Unique identifier of the item
     * @returns {WithClientItemRequestBuilder}
     */
     byClientId(clientId: Guid) : WithClientItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ClientRequestBuilderUriTemplate = "{+baseurl}/client-data-versions/client";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ClientRequestBuilderNavigationMetadata: Record<Exclude<keyof ClientRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byClientId: {
        requestsMetadata: WithClientItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["clientId"],
    },
};
/* tslint:enable */
/* eslint-enable */
