/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithProductItemRequestBuilder, WithProductItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /favorites/clients/{clientId}/products
 */
export interface ProductsRequestBuilder extends BaseRequestBuilder<ProductsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.favorites.clients.item.products.item collection
     * @param productId Unique identifier of the item
     * @returns {WithProductItemRequestBuilder}
     */
     byProductId(productId: Guid) : WithProductItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProductsRequestBuilderUriTemplate = "{+baseurl}/favorites/clients/{clientId}/products";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProductsRequestBuilderNavigationMetadata: Record<Exclude<keyof ProductsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProductId: {
        requestsMetadata: WithProductItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["productId"],
    },
};
/* tslint:enable */
/* eslint-enable */
