/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPaymentResponseFromDiscriminatorValue, type PaymentResponse } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse400Error_errors}
 */
// @ts-ignore
export function createPaymentResponse400Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse400Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse400Error}
 */
// @ts-ignore
export function createPaymentResponse400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse404Error_errors}
 */
// @ts-ignore
export function createPaymentResponse404Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse404Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse404Error}
 */
// @ts-ignore
export function createPaymentResponse404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse405Error_errors}
 */
// @ts-ignore
export function createPaymentResponse405Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse405Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse405Error}
 */
// @ts-ignore
export function createPaymentResponse405ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse405Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse409Error_errors}
 */
// @ts-ignore
export function createPaymentResponse409Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse409Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse409Error}
 */
// @ts-ignore
export function createPaymentResponse409ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse409Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse415Error_errors}
 */
// @ts-ignore
export function createPaymentResponse415Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse415Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse415Error}
 */
// @ts-ignore
export function createPaymentResponse415ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse415Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse500Error_errors}
 */
// @ts-ignore
export function createPaymentResponse500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse500Error}
 */
// @ts-ignore
export function createPaymentResponse500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse502Error_errors}
 */
// @ts-ignore
export function createPaymentResponse502Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse502Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse502Error}
 */
// @ts-ignore
export function createPaymentResponse502ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse502Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse504Error_errors}
 */
// @ts-ignore
export function createPaymentResponse504Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse504Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse504Error}
 */
// @ts-ignore
export function createPaymentResponse504ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse504Error;
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse400Error(paymentResponse400Error: Partial<PaymentResponse400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse400Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse400Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse400Error.errors = n.getCollectionOfObjectValues<PaymentResponse400Error_errors>(createPaymentResponse400Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse400Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse400Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse400Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse400Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse400Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse400Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse400Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse400Error_errors(paymentResponse400Error_errors: Partial<PaymentResponse400Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse400Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse400Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse400Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse404Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse404Error(paymentResponse404Error: Partial<PaymentResponse404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse404Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse404Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse404Error.errors = n.getCollectionOfObjectValues<PaymentResponse404Error_errors>(createPaymentResponse404Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse404Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse404Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse404Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse404Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse404Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse404Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse404Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse404Error_errors(paymentResponse404Error_errors: Partial<PaymentResponse404Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse404Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse404Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse404Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse405Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse405Error(paymentResponse405Error: Partial<PaymentResponse405Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse405Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse405Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse405Error.errors = n.getCollectionOfObjectValues<PaymentResponse405Error_errors>(createPaymentResponse405Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse405Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse405Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse405Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse405Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse405Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse405Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse405Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse405Error_errors(paymentResponse405Error_errors: Partial<PaymentResponse405Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse405Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse405Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse405Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse409Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse409Error(paymentResponse409Error: Partial<PaymentResponse409Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse409Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse409Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse409Error.errors = n.getCollectionOfObjectValues<PaymentResponse409Error_errors>(createPaymentResponse409Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse409Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse409Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse409Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse409Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse409Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse409Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse409Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse409Error_errors(paymentResponse409Error_errors: Partial<PaymentResponse409Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse409Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse409Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse409Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse415Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse415Error(paymentResponse415Error: Partial<PaymentResponse415Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse415Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse415Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse415Error.errors = n.getCollectionOfObjectValues<PaymentResponse415Error_errors>(createPaymentResponse415Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse415Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse415Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse415Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse415Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse415Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse415Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse415Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse415Error_errors(paymentResponse415Error_errors: Partial<PaymentResponse415Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse415Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse415Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse415Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse500Error(paymentResponse500Error: Partial<PaymentResponse500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse500Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse500Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse500Error.errors = n.getCollectionOfObjectValues<PaymentResponse500Error_errors>(createPaymentResponse500Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse500Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse500Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse500Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse500Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse500Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse500Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse500Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse500Error_errors(paymentResponse500Error_errors: Partial<PaymentResponse500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse500Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse500Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse500Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse502Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse502Error(paymentResponse502Error: Partial<PaymentResponse502Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse502Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse502Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse502Error.errors = n.getCollectionOfObjectValues<PaymentResponse502Error_errors>(createPaymentResponse502Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse502Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse502Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse502Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse502Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse502Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse502Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse502Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse502Error_errors(paymentResponse502Error_errors: Partial<PaymentResponse502Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse502Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse502Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse502Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse504Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse504Error(paymentResponse504Error: Partial<PaymentResponse504Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { paymentResponse504Error.code = n.getStringValue(); },
        "detail": n => { paymentResponse504Error.detail = n.getStringValue(); },
        "errors": n => { paymentResponse504Error.errors = n.getCollectionOfObjectValues<PaymentResponse504Error_errors>(createPaymentResponse504Error_errorsFromDiscriminatorValue); },
        "instance": n => { paymentResponse504Error.instance = n.getStringValue(); },
        "missingProperties": n => { paymentResponse504Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { paymentResponse504Error.status = n.getNumberValue(); },
        "title": n => { paymentResponse504Error.title = n.getStringValue(); },
        "traceId": n => { paymentResponse504Error.traceId = n.getStringValue(); },
        "type": n => { paymentResponse504Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse504Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse504Error_errors(paymentResponse504Error_errors: Partial<PaymentResponse504Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { paymentResponse504Error_errors.entity = n.getStringValue(); },
        "message": n => { paymentResponse504Error_errors.message = n.getStringValue(); },
        "name": n => { paymentResponse504Error_errors.name = n.getStringValue(); },
    }
}
export interface PaymentResponse400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse400Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse400Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse404Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse404Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse405Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse405Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse405Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse409Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse409Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse409Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse415Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse415Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse415Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse500Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse500Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse502Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse502Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse502Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PaymentResponse504Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: PaymentResponse504Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface PaymentResponse504Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Builds and executes requests for operations under /payments/{order_id}/pay
 */
export interface PayRequestBuilder extends BaseRequestBuilder<PayRequestBuilder> {
    /**
     * Pay Order
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PaymentResponse>}
     * @throws {PaymentResponse400Error} error when the service returns a 400 status code
     * @throws {PaymentResponse404Error} error when the service returns a 404 status code
     * @throws {PaymentResponse405Error} error when the service returns a 405 status code
     * @throws {PaymentResponse409Error} error when the service returns a 409 status code
     * @throws {PaymentResponse415Error} error when the service returns a 415 status code
     * @throws {PaymentResponse500Error} error when the service returns a 500 status code
     * @throws {PaymentResponse502Error} error when the service returns a 502 status code
     * @throws {PaymentResponse504Error} error when the service returns a 504 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PaymentResponse | undefined>;
    /**
     * Pay Order
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse400Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse400Error(writer: SerializationWriter, paymentResponse400Error: Partial<PaymentResponse400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse400Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse400Error.code);
    writer.writeStringValue("detail", paymentResponse400Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse400Error_errors>("errors", paymentResponse400Error.errors, serializePaymentResponse400Error_errors);
    writer.writeStringValue("instance", paymentResponse400Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse400Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse400Error.status);
    writer.writeStringValue("title", paymentResponse400Error.title);
    writer.writeStringValue("traceId", paymentResponse400Error.traceId);
    writer.writeStringValue("type", paymentResponse400Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse400Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse400Error_errors(writer: SerializationWriter, paymentResponse400Error_errors: Partial<PaymentResponse400Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse400Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse400Error_errors.entity);
    writer.writeStringValue("message", paymentResponse400Error_errors.message);
    writer.writeStringValue("name", paymentResponse400Error_errors.name);
    writer.writeAdditionalData(paymentResponse400Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse404Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse404Error(writer: SerializationWriter, paymentResponse404Error: Partial<PaymentResponse404Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse404Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse404Error.code);
    writer.writeStringValue("detail", paymentResponse404Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse404Error_errors>("errors", paymentResponse404Error.errors, serializePaymentResponse404Error_errors);
    writer.writeStringValue("instance", paymentResponse404Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse404Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse404Error.status);
    writer.writeStringValue("title", paymentResponse404Error.title);
    writer.writeStringValue("traceId", paymentResponse404Error.traceId);
    writer.writeStringValue("type", paymentResponse404Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse404Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse404Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse404Error_errors(writer: SerializationWriter, paymentResponse404Error_errors: Partial<PaymentResponse404Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse404Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse404Error_errors.entity);
    writer.writeStringValue("message", paymentResponse404Error_errors.message);
    writer.writeStringValue("name", paymentResponse404Error_errors.name);
    writer.writeAdditionalData(paymentResponse404Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse405Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse405Error(writer: SerializationWriter, paymentResponse405Error: Partial<PaymentResponse405Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse405Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse405Error.code);
    writer.writeStringValue("detail", paymentResponse405Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse405Error_errors>("errors", paymentResponse405Error.errors, serializePaymentResponse405Error_errors);
    writer.writeStringValue("instance", paymentResponse405Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse405Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse405Error.status);
    writer.writeStringValue("title", paymentResponse405Error.title);
    writer.writeStringValue("traceId", paymentResponse405Error.traceId);
    writer.writeStringValue("type", paymentResponse405Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse405Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse405Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse405Error_errors(writer: SerializationWriter, paymentResponse405Error_errors: Partial<PaymentResponse405Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse405Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse405Error_errors.entity);
    writer.writeStringValue("message", paymentResponse405Error_errors.message);
    writer.writeStringValue("name", paymentResponse405Error_errors.name);
    writer.writeAdditionalData(paymentResponse405Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse409Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse409Error(writer: SerializationWriter, paymentResponse409Error: Partial<PaymentResponse409Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse409Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse409Error.code);
    writer.writeStringValue("detail", paymentResponse409Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse409Error_errors>("errors", paymentResponse409Error.errors, serializePaymentResponse409Error_errors);
    writer.writeStringValue("instance", paymentResponse409Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse409Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse409Error.status);
    writer.writeStringValue("title", paymentResponse409Error.title);
    writer.writeStringValue("traceId", paymentResponse409Error.traceId);
    writer.writeStringValue("type", paymentResponse409Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse409Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse409Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse409Error_errors(writer: SerializationWriter, paymentResponse409Error_errors: Partial<PaymentResponse409Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse409Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse409Error_errors.entity);
    writer.writeStringValue("message", paymentResponse409Error_errors.message);
    writer.writeStringValue("name", paymentResponse409Error_errors.name);
    writer.writeAdditionalData(paymentResponse409Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse415Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse415Error(writer: SerializationWriter, paymentResponse415Error: Partial<PaymentResponse415Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse415Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse415Error.code);
    writer.writeStringValue("detail", paymentResponse415Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse415Error_errors>("errors", paymentResponse415Error.errors, serializePaymentResponse415Error_errors);
    writer.writeStringValue("instance", paymentResponse415Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse415Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse415Error.status);
    writer.writeStringValue("title", paymentResponse415Error.title);
    writer.writeStringValue("traceId", paymentResponse415Error.traceId);
    writer.writeStringValue("type", paymentResponse415Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse415Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse415Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse415Error_errors(writer: SerializationWriter, paymentResponse415Error_errors: Partial<PaymentResponse415Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse415Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse415Error_errors.entity);
    writer.writeStringValue("message", paymentResponse415Error_errors.message);
    writer.writeStringValue("name", paymentResponse415Error_errors.name);
    writer.writeAdditionalData(paymentResponse415Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse500Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse500Error(writer: SerializationWriter, paymentResponse500Error: Partial<PaymentResponse500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse500Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse500Error.code);
    writer.writeStringValue("detail", paymentResponse500Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse500Error_errors>("errors", paymentResponse500Error.errors, serializePaymentResponse500Error_errors);
    writer.writeStringValue("instance", paymentResponse500Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse500Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse500Error.status);
    writer.writeStringValue("title", paymentResponse500Error.title);
    writer.writeStringValue("traceId", paymentResponse500Error.traceId);
    writer.writeStringValue("type", paymentResponse500Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse500Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse500Error_errors(writer: SerializationWriter, paymentResponse500Error_errors: Partial<PaymentResponse500Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse500Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse500Error_errors.entity);
    writer.writeStringValue("message", paymentResponse500Error_errors.message);
    writer.writeStringValue("name", paymentResponse500Error_errors.name);
    writer.writeAdditionalData(paymentResponse500Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse502Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse502Error(writer: SerializationWriter, paymentResponse502Error: Partial<PaymentResponse502Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse502Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse502Error.code);
    writer.writeStringValue("detail", paymentResponse502Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse502Error_errors>("errors", paymentResponse502Error.errors, serializePaymentResponse502Error_errors);
    writer.writeStringValue("instance", paymentResponse502Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse502Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse502Error.status);
    writer.writeStringValue("title", paymentResponse502Error.title);
    writer.writeStringValue("traceId", paymentResponse502Error.traceId);
    writer.writeStringValue("type", paymentResponse502Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse502Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse502Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse502Error_errors(writer: SerializationWriter, paymentResponse502Error_errors: Partial<PaymentResponse502Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse502Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse502Error_errors.entity);
    writer.writeStringValue("message", paymentResponse502Error_errors.message);
    writer.writeStringValue("name", paymentResponse502Error_errors.name);
    writer.writeAdditionalData(paymentResponse502Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse504Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse504Error(writer: SerializationWriter, paymentResponse504Error: Partial<PaymentResponse504Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse504Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", paymentResponse504Error.code);
    writer.writeStringValue("detail", paymentResponse504Error.detail);
    writer.writeCollectionOfObjectValues<PaymentResponse504Error_errors>("errors", paymentResponse504Error.errors, serializePaymentResponse504Error_errors);
    writer.writeStringValue("instance", paymentResponse504Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", paymentResponse504Error.missingProperties);
    writer.writeNumberValue("status", paymentResponse504Error.status);
    writer.writeStringValue("title", paymentResponse504Error.title);
    writer.writeStringValue("traceId", paymentResponse504Error.traceId);
    writer.writeStringValue("type", paymentResponse504Error.type ?? "about:blank");
    writer.writeAdditionalData(paymentResponse504Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse504Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse504Error_errors(writer: SerializationWriter, paymentResponse504Error_errors: Partial<PaymentResponse504Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse504Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", paymentResponse504Error_errors.entity);
    writer.writeStringValue("message", paymentResponse504Error_errors.message);
    writer.writeStringValue("name", paymentResponse504Error_errors.name);
    writer.writeAdditionalData(paymentResponse504Error_errors.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const PayRequestBuilderUriTemplate = "{+baseurl}/payments/{order_id}/pay";
/**
 * Metadata for all the requests in the request builder.
 */
export const PayRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PayRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createPaymentResponse400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createPaymentResponse404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            405: createPaymentResponse405ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createPaymentResponse409ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            415: createPaymentResponse415ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createPaymentResponse500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            502: createPaymentResponse502ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            504: createPaymentResponse504ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPaymentResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
