/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createNotFoundProblemDetailsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, createShoppingCartResponseDtoFromDiscriminatorValue, serializeShoppingCartResponseDto, serializeUpdateShoppingCartRequestDto, type ApiProblemDetails, type NotFoundProblemDetails, type ProblemDetails, type ShoppingCartResponseDto, type UpdateShoppingCartRequestDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /shopping-carts/{clientId}
 */
export interface WithClientItemRequestBuilder extends BaseRequestBuilder<WithClientItemRequestBuilder> {
    /**
     * Creates a new shopping cart for the provided client identifier.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShoppingCartResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShoppingCartResponseDto | undefined>;
    /**
     * Updates shopping cart lines for the provided client identifier.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShoppingCartResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {NotFoundProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     put(body: UpdateShoppingCartRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShoppingCartResponseDto | undefined>;
    /**
     * Creates a new shopping cart for the provided client identifier.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates shopping cart lines for the provided client identifier.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateShoppingCartRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithClientItemRequestBuilderUriTemplate = "{+baseurl}/shopping-carts/{clientId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithClientItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createShoppingCartResponseDtoFromDiscriminatorValue,
    },
    put: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createNotFoundProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createShoppingCartResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateShoppingCartRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
