/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createNotFoundProblemDetailsFromDiscriminatorValue, createOrderResponseDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type ApiProblemDetails, type NotFoundProblemDetails, type OrderResponseDto, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orders/{orderId}
 */
export interface WithOrderItemRequestBuilder extends BaseRequestBuilder<WithOrderItemRequestBuilder> {
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
    /**
     * Returns the order when the Id exists; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrderResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {NotFoundProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrderResponseDto | undefined>;
    /**
     * Returns the order when the Id exists; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithOrderItemRequestBuilderUriTemplate = "{+baseurl}/orders/{orderId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithOrderItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithOrderItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithOrderItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithOrderItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createNotFoundProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrderResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
