/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ClientRequestBuilderNavigationMetadata, type ClientRequestBuilder } from './client/index.js';
// @ts-ignore
import { type WithOrderItemRequestBuilder, WithOrderItemRequestBuilderNavigationMetadata, WithOrderItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orders
 */
export interface OrdersRequestBuilder extends BaseRequestBuilder<OrdersRequestBuilder> {
    /**
     * The client property
     */
    get client(): ClientRequestBuilder;
    /**
     * Gets an item from the ApiSdk.orders.item collection
     * @param orderId Unique identifier of the item
     * @returns {WithOrderItemRequestBuilder}
     */
     byOrderId(orderId: Guid) : WithOrderItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrdersRequestBuilderUriTemplate = "{+baseurl}/orders";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrdersRequestBuilderNavigationMetadata: Record<Exclude<keyof OrdersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOrderId: {
        requestsMetadata: WithOrderItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithOrderItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["orderId"],
    },
    client: {
        navigationMetadata: ClientRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
