/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFlowDescriptorsResponseDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type FlowDescriptorsResponseDto, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orders-documentation/flows
 */
export interface FlowsRequestBuilder extends BaseRequestBuilder<FlowsRequestBuilder> {
    /**
     * Returns flow descriptors mapped by descriptor name.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FlowDescriptorsResponseDto>}
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FlowDescriptorsResponseDto | undefined>;
    /**
     * Returns flow descriptors mapped by descriptor name.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FlowsRequestBuilderUriTemplate = "{+baseurl}/orders-documentation/flows";
/**
 * Metadata for all the requests in the request builder.
 */
export const FlowsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FlowsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFlowDescriptorsResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
