/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHealthResponseFromDiscriminatorValue, type HealthResponse } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HealthResponse405Error_errors}
 */
// @ts-ignore
export function createHealthResponse405Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHealthResponse405Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HealthResponse405Error}
 */
// @ts-ignore
export function createHealthResponse405ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHealthResponse405Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HealthResponse500Error_errors}
 */
// @ts-ignore
export function createHealthResponse500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHealthResponse500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HealthResponse500Error}
 */
// @ts-ignore
export function createHealthResponse500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHealthResponse500Error;
}
/**
 * The deserialization information for the current model
 * @param HealthResponse405Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHealthResponse405Error(healthResponse405Error: Partial<HealthResponse405Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { healthResponse405Error.code = n.getStringValue(); },
        "detail": n => { healthResponse405Error.detail = n.getStringValue(); },
        "errors": n => { healthResponse405Error.errors = n.getCollectionOfObjectValues<HealthResponse405Error_errors>(createHealthResponse405Error_errorsFromDiscriminatorValue); },
        "instance": n => { healthResponse405Error.instance = n.getStringValue(); },
        "missingProperties": n => { healthResponse405Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { healthResponse405Error.status = n.getNumberValue(); },
        "title": n => { healthResponse405Error.title = n.getStringValue(); },
        "traceId": n => { healthResponse405Error.traceId = n.getStringValue(); },
        "type": n => { healthResponse405Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param HealthResponse405Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHealthResponse405Error_errors(healthResponse405Error_errors: Partial<HealthResponse405Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { healthResponse405Error_errors.entity = n.getStringValue(); },
        "message": n => { healthResponse405Error_errors.message = n.getStringValue(); },
        "name": n => { healthResponse405Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param HealthResponse500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHealthResponse500Error(healthResponse500Error: Partial<HealthResponse500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { healthResponse500Error.code = n.getStringValue(); },
        "detail": n => { healthResponse500Error.detail = n.getStringValue(); },
        "errors": n => { healthResponse500Error.errors = n.getCollectionOfObjectValues<HealthResponse500Error_errors>(createHealthResponse500Error_errorsFromDiscriminatorValue); },
        "instance": n => { healthResponse500Error.instance = n.getStringValue(); },
        "missingProperties": n => { healthResponse500Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { healthResponse500Error.status = n.getNumberValue(); },
        "title": n => { healthResponse500Error.title = n.getStringValue(); },
        "traceId": n => { healthResponse500Error.traceId = n.getStringValue(); },
        "type": n => { healthResponse500Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param HealthResponse500Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHealthResponse500Error_errors(healthResponse500Error_errors: Partial<HealthResponse500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { healthResponse500Error_errors.entity = n.getStringValue(); },
        "message": n => { healthResponse500Error_errors.message = n.getStringValue(); },
        "name": n => { healthResponse500Error_errors.name = n.getStringValue(); },
    }
}
export interface HealthResponse405Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: HealthResponse405Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface HealthResponse405Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface HealthResponse500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: HealthResponse500Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface HealthResponse500Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Builds and executes requests for operations under /health/live
 */
export interface LiveRequestBuilder extends BaseRequestBuilder<LiveRequestBuilder> {
    /**
     * Report process liveness without a dependency probe.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<HealthResponse>}
     * @throws {HealthResponse405Error} error when the service returns a 405 status code
     * @throws {HealthResponse500Error} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<HealthResponse | undefined>;
    /**
     * Report process liveness without a dependency probe.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param HealthResponse405Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHealthResponse405Error(writer: SerializationWriter, healthResponse405Error: Partial<HealthResponse405Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!healthResponse405Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", healthResponse405Error.code);
    writer.writeStringValue("detail", healthResponse405Error.detail);
    writer.writeCollectionOfObjectValues<HealthResponse405Error_errors>("errors", healthResponse405Error.errors, serializeHealthResponse405Error_errors);
    writer.writeStringValue("instance", healthResponse405Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", healthResponse405Error.missingProperties);
    writer.writeNumberValue("status", healthResponse405Error.status);
    writer.writeStringValue("title", healthResponse405Error.title);
    writer.writeStringValue("traceId", healthResponse405Error.traceId);
    writer.writeStringValue("type", healthResponse405Error.type ?? "about:blank");
    writer.writeAdditionalData(healthResponse405Error.additionalData);
}
/**
 * Serializes information the current object
 * @param HealthResponse405Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHealthResponse405Error_errors(writer: SerializationWriter, healthResponse405Error_errors: Partial<HealthResponse405Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!healthResponse405Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", healthResponse405Error_errors.entity);
    writer.writeStringValue("message", healthResponse405Error_errors.message);
    writer.writeStringValue("name", healthResponse405Error_errors.name);
    writer.writeAdditionalData(healthResponse405Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param HealthResponse500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHealthResponse500Error(writer: SerializationWriter, healthResponse500Error: Partial<HealthResponse500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!healthResponse500Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", healthResponse500Error.code);
    writer.writeStringValue("detail", healthResponse500Error.detail);
    writer.writeCollectionOfObjectValues<HealthResponse500Error_errors>("errors", healthResponse500Error.errors, serializeHealthResponse500Error_errors);
    writer.writeStringValue("instance", healthResponse500Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", healthResponse500Error.missingProperties);
    writer.writeNumberValue("status", healthResponse500Error.status);
    writer.writeStringValue("title", healthResponse500Error.title);
    writer.writeStringValue("traceId", healthResponse500Error.traceId);
    writer.writeStringValue("type", healthResponse500Error.type ?? "about:blank");
    writer.writeAdditionalData(healthResponse500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param HealthResponse500Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHealthResponse500Error_errors(writer: SerializationWriter, healthResponse500Error_errors: Partial<HealthResponse500Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!healthResponse500Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", healthResponse500Error_errors.entity);
    writer.writeStringValue("message", healthResponse500Error_errors.message);
    writer.writeStringValue("name", healthResponse500Error_errors.name);
    writer.writeAdditionalData(healthResponse500Error_errors.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const LiveRequestBuilderUriTemplate = "{+baseurl}/health/live";
/**
 * Metadata for all the requests in the request builder.
 */
export const LiveRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LiveRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            405: createHealthResponse405ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createHealthResponse500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createHealthResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
