/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ClientsRequestBuilderNavigationMetadata, type ClientsRequestBuilder } from './clients/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /favorites
 */
export interface FavoritesRequestBuilder extends BaseRequestBuilder<FavoritesRequestBuilder> {
    /**
     * The clients property
     */
    get clients(): ClientsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FavoritesRequestBuilderUriTemplate = "{+baseurl}/favorites";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FavoritesRequestBuilderNavigationMetadata: Record<Exclude<keyof FavoritesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    clients: {
        navigationMetadata: ClientsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
