/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createCustomerResponseDtoFromDiscriminatorValue, serializeAddCompanyRequestDto, serializeCustomerResponseDto, type AddCompanyRequestDto, type ApiProblemDetails, type CustomerResponseDto } from '../../../models/index.js';
// @ts-ignore
import { type WithCompanyItemRequestBuilder, WithCompanyItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customers/{customer-id}/companies
 */
export interface CompaniesRequestBuilder extends BaseRequestBuilder<CompaniesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.customers.item.companies.item collection
     * @param companyId Unique identifier of the item
     * @returns {WithCompanyItemRequestBuilder}
     */
     byCompanyId(companyId: Guid) : WithCompanyItemRequestBuilder;
    /**
     * Adds company data. Duplicate tax IDs and concurrent customer changes return 409; a customer removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 404 status code
     * @throws {ApiProblemDetails} error when the service returns a 409 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     post(body: AddCompanyRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CustomerResponseDto | undefined>;
    /**
     * Adds company data. Duplicate tax IDs and concurrent customer changes return 409; a customer removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddCompanyRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CompaniesRequestBuilderUriTemplate = "{+baseurl}/customers/{customer%2Did}/companies";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CompaniesRequestBuilderNavigationMetadata: Record<Exclude<keyof CompaniesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCompanyId: {
        requestsMetadata: WithCompanyItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["companyId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CompaniesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CompaniesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddCompanyRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
