/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FlowsRequestBuilderRequestsMetadata, type FlowsRequestBuilder } from './flows/index.js';
// @ts-ignore
import { type ValidationsRequestBuilder, ValidationsRequestBuilderRequestsMetadata } from './validations/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orders-documentation
 */
export interface OrdersDocumentationRequestBuilder extends BaseRequestBuilder<OrdersDocumentationRequestBuilder> {
    /**
     * The flows property
     */
    get flows(): FlowsRequestBuilder;
    /**
     * The validations property
     */
    get validations(): ValidationsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrdersDocumentationRequestBuilderUriTemplate = "{+baseurl}/orders-documentation";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrdersDocumentationRequestBuilderNavigationMetadata: Record<Exclude<keyof OrdersDocumentationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    flows: {
        requestsMetadata: FlowsRequestBuilderRequestsMetadata,
    },
    validations: {
        requestsMetadata: ValidationsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
