/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createMobilePhoneDetailsDtoFromDiscriminatorValue, createMobilePhoneDtoFromDiscriminatorValue, serializeCreateMobilePhoneExternalDto, serializeMobilePhoneDetailsDto, type ApiProblemDetails, type CreateMobilePhoneExternalDto, type MobilePhoneDetailsDto, type MobilePhoneDto } from '../models/index.js';
// @ts-ignore
import { ByIdsRequestBuilderRequestsMetadata, type ByIdsRequestBuilder } from './byIds/index.js';
// @ts-ignore
import { FilterRequestBuilderRequestsMetadata, type FilterRequestBuilder } from './filter/index.js';
// @ts-ignore
import { MobilePhonesItemRequestBuilderNavigationMetadata, MobilePhonesItemRequestBuilderRequestsMetadata, type MobilePhonesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { TopRequestBuilderRequestsMetadata, type TopRequestBuilder } from './top/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /mobile-phones
 */
export interface MobilePhonesRequestBuilder extends BaseRequestBuilder<MobilePhonesRequestBuilder> {
    /**
     * The byIds property
     */
    get byIds(): ByIdsRequestBuilder;
    /**
     * The filter property
     */
    get filter(): FilterRequestBuilder;
    /**
     * The top property
     */
    get top(): TopRequestBuilder;
    /**
     * Gets an item from the ApiSdk.mobilePhones.item collection
     * @param id Unique identifier of the item
     * @returns {MobilePhonesItemRequestBuilder}
     */
     byId(id: Guid) : MobilePhonesItemRequestBuilder;
    /**
     * Returns up to the requested amount of active mobile phones ordered by name, then Id.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MobilePhoneDto[]>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<MobilePhonesRequestBuilderGetQueryParameters> | undefined) : Promise<MobilePhoneDto[] | undefined>;
    /**
     * Creates a new mobile phone and returns the created resource.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MobilePhoneDetailsDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     post(body: CreateMobilePhoneExternalDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MobilePhoneDetailsDto | undefined>;
    /**
     * Returns up to the requested amount of active mobile phones ordered by name, then Id.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<MobilePhonesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Creates a new mobile phone and returns the created resource.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateMobilePhoneExternalDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns up to the requested amount of active mobile phones ordered by name, then Id.
 */
export interface MobilePhonesRequestBuilderGetQueryParameters {
    amount?: number;
}
/**
 * Uri template for the request builder.
 */
export const MobilePhonesRequestBuilderUriTemplate = "{+baseurl}/mobile-phones";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MobilePhonesRequestBuilderNavigationMetadata: Record<Exclude<keyof MobilePhonesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: MobilePhonesItemRequestBuilderRequestsMetadata,
        navigationMetadata: MobilePhonesItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    byIds: {
        requestsMetadata: ByIdsRequestBuilderRequestsMetadata,
    },
    filter: {
        requestsMetadata: FilterRequestBuilderRequestsMetadata,
    },
    top: {
        requestsMetadata: TopRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MobilePhonesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: "{+baseurl}/mobile-phones?amount={amount}",
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMobilePhoneDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: MobilePhonesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMobilePhoneDetailsDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateMobilePhoneExternalDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
