/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWebhookAcknowledgementFromDiscriminatorValue, serializeWebhookAcknowledgement, type WebhookAcknowledgement } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StripePostRequestBody}
 */
// @ts-ignore
export function createStripePostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStripePostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement400Error_errors}
 */
// @ts-ignore
export function createWebhookAcknowledgement400Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement400Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement400Error}
 */
// @ts-ignore
export function createWebhookAcknowledgement400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement405Error_errors}
 */
// @ts-ignore
export function createWebhookAcknowledgement405Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement405Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement405Error}
 */
// @ts-ignore
export function createWebhookAcknowledgement405ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement405Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement413Error_errors}
 */
// @ts-ignore
export function createWebhookAcknowledgement413Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement413Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement413Error}
 */
// @ts-ignore
export function createWebhookAcknowledgement413ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement413Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement415Error_errors}
 */
// @ts-ignore
export function createWebhookAcknowledgement415Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement415Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement415Error}
 */
// @ts-ignore
export function createWebhookAcknowledgement415ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement415Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement500Error_errors}
 */
// @ts-ignore
export function createWebhookAcknowledgement500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement500Error}
 */
// @ts-ignore
export function createWebhookAcknowledgement500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement503Error_errors}
 */
// @ts-ignore
export function createWebhookAcknowledgement503Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement503Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookAcknowledgement503Error}
 */
// @ts-ignore
export function createWebhookAcknowledgement503ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookAcknowledgement503Error;
}
/**
 * The deserialization information for the current model
 * @param StripePostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStripePostRequestBody(stripePostRequestBody: Partial<StripePostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement400Error(webhookAcknowledgement400Error: Partial<WebhookAcknowledgement400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { webhookAcknowledgement400Error.code = n.getStringValue(); },
        "detail": n => { webhookAcknowledgement400Error.detail = n.getStringValue(); },
        "errors": n => { webhookAcknowledgement400Error.errors = n.getCollectionOfObjectValues<WebhookAcknowledgement400Error_errors>(createWebhookAcknowledgement400Error_errorsFromDiscriminatorValue); },
        "instance": n => { webhookAcknowledgement400Error.instance = n.getStringValue(); },
        "missingProperties": n => { webhookAcknowledgement400Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { webhookAcknowledgement400Error.status = n.getNumberValue(); },
        "title": n => { webhookAcknowledgement400Error.title = n.getStringValue(); },
        "traceId": n => { webhookAcknowledgement400Error.traceId = n.getStringValue(); },
        "type": n => { webhookAcknowledgement400Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement400Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement400Error_errors(webhookAcknowledgement400Error_errors: Partial<WebhookAcknowledgement400Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { webhookAcknowledgement400Error_errors.entity = n.getStringValue(); },
        "message": n => { webhookAcknowledgement400Error_errors.message = n.getStringValue(); },
        "name": n => { webhookAcknowledgement400Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement405Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement405Error(webhookAcknowledgement405Error: Partial<WebhookAcknowledgement405Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { webhookAcknowledgement405Error.code = n.getStringValue(); },
        "detail": n => { webhookAcknowledgement405Error.detail = n.getStringValue(); },
        "errors": n => { webhookAcknowledgement405Error.errors = n.getCollectionOfObjectValues<WebhookAcknowledgement405Error_errors>(createWebhookAcknowledgement405Error_errorsFromDiscriminatorValue); },
        "instance": n => { webhookAcknowledgement405Error.instance = n.getStringValue(); },
        "missingProperties": n => { webhookAcknowledgement405Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { webhookAcknowledgement405Error.status = n.getNumberValue(); },
        "title": n => { webhookAcknowledgement405Error.title = n.getStringValue(); },
        "traceId": n => { webhookAcknowledgement405Error.traceId = n.getStringValue(); },
        "type": n => { webhookAcknowledgement405Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement405Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement405Error_errors(webhookAcknowledgement405Error_errors: Partial<WebhookAcknowledgement405Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { webhookAcknowledgement405Error_errors.entity = n.getStringValue(); },
        "message": n => { webhookAcknowledgement405Error_errors.message = n.getStringValue(); },
        "name": n => { webhookAcknowledgement405Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement413Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement413Error(webhookAcknowledgement413Error: Partial<WebhookAcknowledgement413Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { webhookAcknowledgement413Error.code = n.getStringValue(); },
        "detail": n => { webhookAcknowledgement413Error.detail = n.getStringValue(); },
        "errors": n => { webhookAcknowledgement413Error.errors = n.getCollectionOfObjectValues<WebhookAcknowledgement413Error_errors>(createWebhookAcknowledgement413Error_errorsFromDiscriminatorValue); },
        "instance": n => { webhookAcknowledgement413Error.instance = n.getStringValue(); },
        "missingProperties": n => { webhookAcknowledgement413Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { webhookAcknowledgement413Error.status = n.getNumberValue(); },
        "title": n => { webhookAcknowledgement413Error.title = n.getStringValue(); },
        "traceId": n => { webhookAcknowledgement413Error.traceId = n.getStringValue(); },
        "type": n => { webhookAcknowledgement413Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement413Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement413Error_errors(webhookAcknowledgement413Error_errors: Partial<WebhookAcknowledgement413Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { webhookAcknowledgement413Error_errors.entity = n.getStringValue(); },
        "message": n => { webhookAcknowledgement413Error_errors.message = n.getStringValue(); },
        "name": n => { webhookAcknowledgement413Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement415Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement415Error(webhookAcknowledgement415Error: Partial<WebhookAcknowledgement415Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { webhookAcknowledgement415Error.code = n.getStringValue(); },
        "detail": n => { webhookAcknowledgement415Error.detail = n.getStringValue(); },
        "errors": n => { webhookAcknowledgement415Error.errors = n.getCollectionOfObjectValues<WebhookAcknowledgement415Error_errors>(createWebhookAcknowledgement415Error_errorsFromDiscriminatorValue); },
        "instance": n => { webhookAcknowledgement415Error.instance = n.getStringValue(); },
        "missingProperties": n => { webhookAcknowledgement415Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { webhookAcknowledgement415Error.status = n.getNumberValue(); },
        "title": n => { webhookAcknowledgement415Error.title = n.getStringValue(); },
        "traceId": n => { webhookAcknowledgement415Error.traceId = n.getStringValue(); },
        "type": n => { webhookAcknowledgement415Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement415Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement415Error_errors(webhookAcknowledgement415Error_errors: Partial<WebhookAcknowledgement415Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { webhookAcknowledgement415Error_errors.entity = n.getStringValue(); },
        "message": n => { webhookAcknowledgement415Error_errors.message = n.getStringValue(); },
        "name": n => { webhookAcknowledgement415Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement500Error(webhookAcknowledgement500Error: Partial<WebhookAcknowledgement500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { webhookAcknowledgement500Error.code = n.getStringValue(); },
        "detail": n => { webhookAcknowledgement500Error.detail = n.getStringValue(); },
        "errors": n => { webhookAcknowledgement500Error.errors = n.getCollectionOfObjectValues<WebhookAcknowledgement500Error_errors>(createWebhookAcknowledgement500Error_errorsFromDiscriminatorValue); },
        "instance": n => { webhookAcknowledgement500Error.instance = n.getStringValue(); },
        "missingProperties": n => { webhookAcknowledgement500Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { webhookAcknowledgement500Error.status = n.getNumberValue(); },
        "title": n => { webhookAcknowledgement500Error.title = n.getStringValue(); },
        "traceId": n => { webhookAcknowledgement500Error.traceId = n.getStringValue(); },
        "type": n => { webhookAcknowledgement500Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement500Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement500Error_errors(webhookAcknowledgement500Error_errors: Partial<WebhookAcknowledgement500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { webhookAcknowledgement500Error_errors.entity = n.getStringValue(); },
        "message": n => { webhookAcknowledgement500Error_errors.message = n.getStringValue(); },
        "name": n => { webhookAcknowledgement500Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement503Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement503Error(webhookAcknowledgement503Error: Partial<WebhookAcknowledgement503Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { webhookAcknowledgement503Error.code = n.getStringValue(); },
        "detail": n => { webhookAcknowledgement503Error.detail = n.getStringValue(); },
        "errors": n => { webhookAcknowledgement503Error.errors = n.getCollectionOfObjectValues<WebhookAcknowledgement503Error_errors>(createWebhookAcknowledgement503Error_errorsFromDiscriminatorValue); },
        "instance": n => { webhookAcknowledgement503Error.instance = n.getStringValue(); },
        "missingProperties": n => { webhookAcknowledgement503Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { webhookAcknowledgement503Error.status = n.getNumberValue(); },
        "title": n => { webhookAcknowledgement503Error.title = n.getStringValue(); },
        "traceId": n => { webhookAcknowledgement503Error.traceId = n.getStringValue(); },
        "type": n => { webhookAcknowledgement503Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookAcknowledgement503Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookAcknowledgement503Error_errors(webhookAcknowledgement503Error_errors: Partial<WebhookAcknowledgement503Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { webhookAcknowledgement503Error_errors.entity = n.getStringValue(); },
        "message": n => { webhookAcknowledgement503Error_errors.message = n.getStringValue(); },
        "name": n => { webhookAcknowledgement503Error_errors.name = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StripePostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStripePostRequestBody(writer: SerializationWriter, stripePostRequestBody: Partial<StripePostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!stripePostRequestBody || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(stripePostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement400Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement400Error(writer: SerializationWriter, webhookAcknowledgement400Error: Partial<WebhookAcknowledgement400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement400Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", webhookAcknowledgement400Error.code);
    writer.writeStringValue("detail", webhookAcknowledgement400Error.detail);
    writer.writeCollectionOfObjectValues<WebhookAcknowledgement400Error_errors>("errors", webhookAcknowledgement400Error.errors, serializeWebhookAcknowledgement400Error_errors);
    writer.writeStringValue("instance", webhookAcknowledgement400Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", webhookAcknowledgement400Error.missingProperties);
    writer.writeNumberValue("status", webhookAcknowledgement400Error.status);
    writer.writeStringValue("title", webhookAcknowledgement400Error.title);
    writer.writeStringValue("traceId", webhookAcknowledgement400Error.traceId);
    writer.writeStringValue("type", webhookAcknowledgement400Error.type ?? "about:blank");
    writer.writeAdditionalData(webhookAcknowledgement400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement400Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement400Error_errors(writer: SerializationWriter, webhookAcknowledgement400Error_errors: Partial<WebhookAcknowledgement400Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement400Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", webhookAcknowledgement400Error_errors.entity);
    writer.writeStringValue("message", webhookAcknowledgement400Error_errors.message);
    writer.writeStringValue("name", webhookAcknowledgement400Error_errors.name);
    writer.writeAdditionalData(webhookAcknowledgement400Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement405Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement405Error(writer: SerializationWriter, webhookAcknowledgement405Error: Partial<WebhookAcknowledgement405Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement405Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", webhookAcknowledgement405Error.code);
    writer.writeStringValue("detail", webhookAcknowledgement405Error.detail);
    writer.writeCollectionOfObjectValues<WebhookAcknowledgement405Error_errors>("errors", webhookAcknowledgement405Error.errors, serializeWebhookAcknowledgement405Error_errors);
    writer.writeStringValue("instance", webhookAcknowledgement405Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", webhookAcknowledgement405Error.missingProperties);
    writer.writeNumberValue("status", webhookAcknowledgement405Error.status);
    writer.writeStringValue("title", webhookAcknowledgement405Error.title);
    writer.writeStringValue("traceId", webhookAcknowledgement405Error.traceId);
    writer.writeStringValue("type", webhookAcknowledgement405Error.type ?? "about:blank");
    writer.writeAdditionalData(webhookAcknowledgement405Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement405Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement405Error_errors(writer: SerializationWriter, webhookAcknowledgement405Error_errors: Partial<WebhookAcknowledgement405Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement405Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", webhookAcknowledgement405Error_errors.entity);
    writer.writeStringValue("message", webhookAcknowledgement405Error_errors.message);
    writer.writeStringValue("name", webhookAcknowledgement405Error_errors.name);
    writer.writeAdditionalData(webhookAcknowledgement405Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement413Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement413Error(writer: SerializationWriter, webhookAcknowledgement413Error: Partial<WebhookAcknowledgement413Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement413Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", webhookAcknowledgement413Error.code);
    writer.writeStringValue("detail", webhookAcknowledgement413Error.detail);
    writer.writeCollectionOfObjectValues<WebhookAcknowledgement413Error_errors>("errors", webhookAcknowledgement413Error.errors, serializeWebhookAcknowledgement413Error_errors);
    writer.writeStringValue("instance", webhookAcknowledgement413Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", webhookAcknowledgement413Error.missingProperties);
    writer.writeNumberValue("status", webhookAcknowledgement413Error.status);
    writer.writeStringValue("title", webhookAcknowledgement413Error.title);
    writer.writeStringValue("traceId", webhookAcknowledgement413Error.traceId);
    writer.writeStringValue("type", webhookAcknowledgement413Error.type ?? "about:blank");
    writer.writeAdditionalData(webhookAcknowledgement413Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement413Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement413Error_errors(writer: SerializationWriter, webhookAcknowledgement413Error_errors: Partial<WebhookAcknowledgement413Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement413Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", webhookAcknowledgement413Error_errors.entity);
    writer.writeStringValue("message", webhookAcknowledgement413Error_errors.message);
    writer.writeStringValue("name", webhookAcknowledgement413Error_errors.name);
    writer.writeAdditionalData(webhookAcknowledgement413Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement415Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement415Error(writer: SerializationWriter, webhookAcknowledgement415Error: Partial<WebhookAcknowledgement415Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement415Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", webhookAcknowledgement415Error.code);
    writer.writeStringValue("detail", webhookAcknowledgement415Error.detail);
    writer.writeCollectionOfObjectValues<WebhookAcknowledgement415Error_errors>("errors", webhookAcknowledgement415Error.errors, serializeWebhookAcknowledgement415Error_errors);
    writer.writeStringValue("instance", webhookAcknowledgement415Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", webhookAcknowledgement415Error.missingProperties);
    writer.writeNumberValue("status", webhookAcknowledgement415Error.status);
    writer.writeStringValue("title", webhookAcknowledgement415Error.title);
    writer.writeStringValue("traceId", webhookAcknowledgement415Error.traceId);
    writer.writeStringValue("type", webhookAcknowledgement415Error.type ?? "about:blank");
    writer.writeAdditionalData(webhookAcknowledgement415Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement415Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement415Error_errors(writer: SerializationWriter, webhookAcknowledgement415Error_errors: Partial<WebhookAcknowledgement415Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement415Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", webhookAcknowledgement415Error_errors.entity);
    writer.writeStringValue("message", webhookAcknowledgement415Error_errors.message);
    writer.writeStringValue("name", webhookAcknowledgement415Error_errors.name);
    writer.writeAdditionalData(webhookAcknowledgement415Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement500Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement500Error(writer: SerializationWriter, webhookAcknowledgement500Error: Partial<WebhookAcknowledgement500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement500Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", webhookAcknowledgement500Error.code);
    writer.writeStringValue("detail", webhookAcknowledgement500Error.detail);
    writer.writeCollectionOfObjectValues<WebhookAcknowledgement500Error_errors>("errors", webhookAcknowledgement500Error.errors, serializeWebhookAcknowledgement500Error_errors);
    writer.writeStringValue("instance", webhookAcknowledgement500Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", webhookAcknowledgement500Error.missingProperties);
    writer.writeNumberValue("status", webhookAcknowledgement500Error.status);
    writer.writeStringValue("title", webhookAcknowledgement500Error.title);
    writer.writeStringValue("traceId", webhookAcknowledgement500Error.traceId);
    writer.writeStringValue("type", webhookAcknowledgement500Error.type ?? "about:blank");
    writer.writeAdditionalData(webhookAcknowledgement500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement500Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement500Error_errors(writer: SerializationWriter, webhookAcknowledgement500Error_errors: Partial<WebhookAcknowledgement500Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement500Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", webhookAcknowledgement500Error_errors.entity);
    writer.writeStringValue("message", webhookAcknowledgement500Error_errors.message);
    writer.writeStringValue("name", webhookAcknowledgement500Error_errors.name);
    writer.writeAdditionalData(webhookAcknowledgement500Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement503Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement503Error(writer: SerializationWriter, webhookAcknowledgement503Error: Partial<WebhookAcknowledgement503Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement503Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", webhookAcknowledgement503Error.code);
    writer.writeStringValue("detail", webhookAcknowledgement503Error.detail);
    writer.writeCollectionOfObjectValues<WebhookAcknowledgement503Error_errors>("errors", webhookAcknowledgement503Error.errors, serializeWebhookAcknowledgement503Error_errors);
    writer.writeStringValue("instance", webhookAcknowledgement503Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", webhookAcknowledgement503Error.missingProperties);
    writer.writeNumberValue("status", webhookAcknowledgement503Error.status);
    writer.writeStringValue("title", webhookAcknowledgement503Error.title);
    writer.writeStringValue("traceId", webhookAcknowledgement503Error.traceId);
    writer.writeStringValue("type", webhookAcknowledgement503Error.type ?? "about:blank");
    writer.writeAdditionalData(webhookAcknowledgement503Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookAcknowledgement503Error_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookAcknowledgement503Error_errors(writer: SerializationWriter, webhookAcknowledgement503Error_errors: Partial<WebhookAcknowledgement503Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookAcknowledgement503Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", webhookAcknowledgement503Error_errors.entity);
    writer.writeStringValue("message", webhookAcknowledgement503Error_errors.message);
    writer.writeStringValue("name", webhookAcknowledgement503Error_errors.name);
    writer.writeAdditionalData(webhookAcknowledgement503Error_errors.additionalData);
}
export interface StripePostRequestBody extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /payments/webhooks/stripe
 */
export interface StripeRequestBuilder extends BaseRequestBuilder<StripeRequestBuilder> {
    /**
     * Receive the original signed bytes without contacting Orders, invoices or Stripe.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WebhookAcknowledgement>}
     * @throws {WebhookAcknowledgement400Error} error when the service returns a 400 status code
     * @throws {WebhookAcknowledgement405Error} error when the service returns a 405 status code
     * @throws {WebhookAcknowledgement413Error} error when the service returns a 413 status code
     * @throws {WebhookAcknowledgement415Error} error when the service returns a 415 status code
     * @throws {WebhookAcknowledgement500Error} error when the service returns a 500 status code
     * @throws {WebhookAcknowledgement503Error} error when the service returns a 503 status code
     */
     post(body: StripePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WebhookAcknowledgement | undefined>;
    /**
     * Receive the original signed bytes without contacting Orders, invoices or Stripe.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: StripePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface WebhookAcknowledgement400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: WebhookAcknowledgement400Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface WebhookAcknowledgement400Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface WebhookAcknowledgement405Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: WebhookAcknowledgement405Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface WebhookAcknowledgement405Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface WebhookAcknowledgement413Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: WebhookAcknowledgement413Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface WebhookAcknowledgement413Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface WebhookAcknowledgement415Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: WebhookAcknowledgement415Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface WebhookAcknowledgement415Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface WebhookAcknowledgement500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: WebhookAcknowledgement500Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface WebhookAcknowledgement500Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface WebhookAcknowledgement503Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: WebhookAcknowledgement503Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface WebhookAcknowledgement503Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Uri template for the request builder.
 */
export const StripeRequestBuilderUriTemplate = "{+baseurl}/payments/webhooks/stripe";
/**
 * Metadata for all the requests in the request builder.
 */
export const StripeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: StripeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createWebhookAcknowledgement400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            405: createWebhookAcknowledgement405ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createWebhookAcknowledgement413ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            415: createWebhookAcknowledgement415ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createWebhookAcknowledgement500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createWebhookAcknowledgement503ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWebhookAcknowledgementFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeStripePostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
