/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createConflictProblemDetailsFromDiscriminatorValue, createFavoriteResponseDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeAddFavoriteRequestDto, serializeFavoriteResponseDto, type AddFavoriteRequestDto, type ApiProblemDetails, type ConflictProblemDetails, type FavoriteResponseDto, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { ProductsRequestBuilderNavigationMetadata, type ProductsRequestBuilder } from './products/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /favorites/clients/{clientId}
 */
export interface WithClientItemRequestBuilder extends BaseRequestBuilder<WithClientItemRequestBuilder> {
    /**
     * The products property
     */
    get products(): ProductsRequestBuilder;
    /**
     * Removes all saved product favorites for a specific client.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Retrieves all favorited product entries for a specified client identifier.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FavoriteResponseDto[]>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FavoriteResponseDto[] | undefined>;
    /**
     * Adds a product reference to the customer's favorites list.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FavoriteResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ConflictProblemDetails} error when the service returns a 409 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: AddFavoriteRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FavoriteResponseDto | undefined>;
    /**
     * Removes all saved product favorites for a specific client.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Retrieves all favorited product entries for a specified client identifier.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Adds a product reference to the customer's favorites list.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddFavoriteRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithClientItemRequestBuilderUriTemplate = "{+baseurl}/favorites/clients/{clientId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithClientItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithClientItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    products: {
        navigationMetadata: ProductsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithClientItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFavoriteResponseDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createConflictProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFavoriteResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddFavoriteRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
