/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createValidationDescriptorsResponseDtoFromDiscriminatorValue, type ProblemDetails, type ValidationDescriptorsResponseDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users-documentation/validations
 */
export interface ValidationsRequestBuilder extends BaseRequestBuilder<ValidationsRequestBuilder> {
    /**
     * Returns validation descriptors mapped by policy name.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ValidationDescriptorsResponseDto>}
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ValidationDescriptorsResponseDto | undefined>;
    /**
     * Returns validation descriptors mapped by policy name.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ValidationsRequestBuilderUriTemplate = "{+baseurl}/users-documentation/validations";
/**
 * Metadata for all the requests in the request builder.
 */
export const ValidationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ValidationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createValidationDescriptorsResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
