/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createTopMobilePhoneDtoFromDiscriminatorValue, type ApiProblemDetails, type TopMobilePhoneDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /mobile-phones/top
 */
export interface TopRequestBuilder extends BaseRequestBuilder<TopRequestBuilder> {
    /**
     * Returns the three most recently changed active mobile phones, ordered by ChangedAt descending, then Id descending. Top means recent changes, not sales popularity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TopMobilePhoneDto[]>}
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TopMobilePhoneDto[] | undefined>;
    /**
     * Returns the three most recently changed active mobile phones, ordered by ChangedAt descending, then Id descending. Top means recent changes, not sales popularity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TopRequestBuilderUriTemplate = "{+baseurl}/mobile-phones/top";
/**
 * Metadata for all the requests in the request builder.
 */
export const TopRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TopRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTopMobilePhoneDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
