/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HealthResponse}
 */
// @ts-ignore
export function createHealthResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHealthResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentResponse}
 */
// @ts-ignore
export function createPaymentResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentResponse;
}
/**
 * The deserialization information for the current model
 * @param HealthResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHealthResponse(healthResponse: Partial<HealthResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "status": n => { healthResponse.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaymentResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentResponse(paymentResponse: Partial<PaymentResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "amount_minor": n => { paymentResponse.amountMinor = n.getNumberValue(); },
        "created_at": n => { paymentResponse.createdAt = n.getDateValue(); },
        "currency": n => { paymentResponse.currency = n.getStringValue(); },
        "failure_code": n => { paymentResponse.failureCode = n.getStringValue(); },
        "id": n => { paymentResponse.id = n.getGuidValue(); },
        "order_id": n => { paymentResponse.orderId = n.getGuidValue(); },
        "provider_payment_id": n => { paymentResponse.providerPaymentId = n.getStringValue(); },
        "provider_session_id": n => { paymentResponse.providerSessionId = n.getStringValue(); },
        "status": n => { paymentResponse.status = n.getStringValue(); },
        "updated_at": n => { paymentResponse.updatedAt = n.getDateValue(); },
    }
}
export interface HealthResponse extends AdditionalDataHolder, Parsable {
    /**
     * The status property
     */
    status?: string | null;
}
export interface PaymentResponse extends AdditionalDataHolder, Parsable {
    /**
     * The amount_minor property
     */
    amountMinor?: number | null;
    /**
     * The created_at property
     */
    createdAt?: Date | null;
    /**
     * The currency property
     */
    currency?: string | null;
    /**
     * The failure_code property
     */
    failureCode?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The order_id property
     */
    orderId?: Guid | null;
    /**
     * The provider_payment_id property
     */
    providerPaymentId?: string | null;
    /**
     * The provider_session_id property
     */
    providerSessionId?: string | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The updated_at property
     */
    updatedAt?: Date | null;
}
/**
 * Serializes information the current object
 * @param HealthResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHealthResponse(writer: SerializationWriter, healthResponse: Partial<HealthResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!healthResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("status", healthResponse.status);
    writer.writeAdditionalData(healthResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaymentResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentResponse(writer: SerializationWriter, paymentResponse: Partial<PaymentResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paymentResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("amount_minor", paymentResponse.amountMinor);
    writer.writeDateValue("created_at", paymentResponse.createdAt);
    writer.writeStringValue("currency", paymentResponse.currency);
    writer.writeStringValue("failure_code", paymentResponse.failureCode);
    writer.writeGuidValue("id", paymentResponse.id);
    writer.writeGuidValue("order_id", paymentResponse.orderId);
    writer.writeStringValue("provider_payment_id", paymentResponse.providerPaymentId);
    writer.writeStringValue("provider_session_id", paymentResponse.providerSessionId);
    writer.writeStringValue("status", paymentResponse.status);
    writer.writeDateValue("updated_at", paymentResponse.updatedAt);
    writer.writeAdditionalData(paymentResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
