/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CategoriesRequestBuilderNavigationMetadata, CategoriesRequestBuilderRequestsMetadata, type CategoriesRequestBuilder } from './categories/index.js';
// @ts-ignore
import { CurrenciesRequestBuilderNavigationMetadata, CurrenciesRequestBuilderRequestsMetadata, type CurrenciesRequestBuilder } from './currencies/index.js';
// @ts-ignore
import { MobilePhonesRequestBuilderNavigationMetadata, MobilePhonesRequestBuilderRequestsMetadata, type MobilePhonesRequestBuilder } from './mobilePhones/index.js';
// @ts-ignore
import { ProductsDocumentationRequestBuilderNavigationMetadata, type ProductsDocumentationRequestBuilder } from './productsDocumentation/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link ProductsApiClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createProductsApiClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<ProductsApiClient>(requestAdapter, pathParameters, ProductsApiClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface ProductsApiClient extends BaseRequestBuilder<ProductsApiClient> {
    /**
     * The categories property
     */
    get categories(): CategoriesRequestBuilder;
    /**
     * The currencies property
     */
    get currencies(): CurrenciesRequestBuilder;
    /**
     * The mobilePhones property
     */
    get mobilePhones(): MobilePhonesRequestBuilder;
    /**
     * The productsDocumentation property
     */
    get productsDocumentation(): ProductsDocumentationRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProductsApiClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProductsApiClientNavigationMetadata: Record<Exclude<keyof ProductsApiClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    categories: {
        requestsMetadata: CategoriesRequestBuilderRequestsMetadata,
        navigationMetadata: CategoriesRequestBuilderNavigationMetadata,
    },
    currencies: {
        requestsMetadata: CurrenciesRequestBuilderRequestsMetadata,
        navigationMetadata: CurrenciesRequestBuilderNavigationMetadata,
    },
    mobilePhones: {
        requestsMetadata: MobilePhonesRequestBuilderRequestsMetadata,
        navigationMetadata: MobilePhonesRequestBuilderNavigationMetadata,
    },
    productsDocumentation: {
        navigationMetadata: ProductsDocumentationRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
