/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ClientItemRequestBuilderNavigationMetadata, ClientItemRequestBuilderRequestsMetadata, type ClientItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invoices
 */
export interface InvoicesRequestBuilder extends BaseRequestBuilder<InvoicesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.invoices.item collection
     * @param clientId Unique identifier of the item
     * @returns {ClientItemRequestBuilder}
     */
     byClientId(clientId: Guid) : ClientItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const InvoicesRequestBuilderUriTemplate = "{+baseurl}/invoices";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InvoicesRequestBuilderNavigationMetadata: Record<Exclude<keyof InvoicesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byClientId: {
        requestsMetadata: ClientItemRequestBuilderRequestsMetadata,
        navigationMetadata: ClientItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["client%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
