/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createInvoiceResponseDtoFromDiscriminatorValue, createNotFoundProblemDetailsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type ApiProblemDetails, type InvoiceResponseDto, type NotFoundProblemDetails, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type WithOrderItemRequestBuilder, WithOrderItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invoices/{client-id}
 */
export interface ClientItemRequestBuilder extends BaseRequestBuilder<ClientItemRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.invoices.item.item collection
     * @param orderId Unique identifier of the item
     * @returns {WithOrderItemRequestBuilder}
     */
     byOrderId(orderId: Guid) : WithOrderItemRequestBuilder;
    /**
     * Returns the invoice when the Id exists; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InvoiceResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {NotFoundProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InvoiceResponseDto | undefined>;
    /**
     * Returns the invoice when the Id exists; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ClientItemRequestBuilderUriTemplate = "{+baseurl}/invoices/{client%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ClientItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ClientItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOrderId: {
        requestsMetadata: WithOrderItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["orderId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ClientItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createNotFoundProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInvoiceResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
