/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CompaniesRequestBuilderNavigationMetadata, CompaniesRequestBuilderRequestsMetadata, type CompaniesRequestBuilder } from './companies/index.js';
// @ts-ignore
import { IndividualRequestBuilderRequestsMetadata, type IndividualRequestBuilder } from './individual/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customers/{customer-id}
 */
export interface CustomerItemRequestBuilder extends BaseRequestBuilder<CustomerItemRequestBuilder> {
    /**
     * The companies property
     */
    get companies(): CompaniesRequestBuilder;
    /**
     * The individual property
     */
    get individual(): IndividualRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CustomerItemRequestBuilderUriTemplate = "{+baseurl}/customers/{customer%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CustomerItemRequestBuilderNavigationMetadata: Record<Exclude<keyof CustomerItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    companies: {
        requestsMetadata: CompaniesRequestBuilderRequestsMetadata,
        navigationMetadata: CompaniesRequestBuilderNavigationMetadata,
    },
    individual: {
        requestsMetadata: IndividualRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
