/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createClientDataVersionResponseDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeClientDataVersionResponseDto, serializeCreateClientDataVersionRequestDto, type ApiProblemDetails, type ClientDataVersionResponseDto, type CreateClientDataVersionRequestDto, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /client-data-versions/{clientId}
 */
export interface WithClientItemRequestBuilder extends BaseRequestBuilder<WithClientItemRequestBuilder> {
    /**
     * Creates a new client data version for the provided client identifier.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ClientDataVersionResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: CreateClientDataVersionRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ClientDataVersionResponseDto | undefined>;
    /**
     * Creates a new client data version for the provided client identifier.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateClientDataVersionRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithClientItemRequestBuilderUriTemplate = "{+baseurl}/client-data-versions/{clientId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithClientItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createClientDataVersionResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateClientDataVersionRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
