/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCheckoutResponseFromDiscriminatorValue, type CheckoutResponse } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /payments/{order_id}/checkout
 */
export interface CheckoutRequestBuilder extends BaseRequestBuilder<CheckoutRequestBuilder> {
    /**
     * Create Order Checkout
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CheckoutResponse>}
     * @throws {CheckoutResponse400Error} error when the service returns a 400 status code
     * @throws {CheckoutResponse404Error} error when the service returns a 404 status code
     * @throws {CheckoutResponse405Error} error when the service returns a 405 status code
     * @throws {CheckoutResponse409Error} error when the service returns a 409 status code
     * @throws {CheckoutResponse415Error} error when the service returns a 415 status code
     * @throws {CheckoutResponse500Error} error when the service returns a 500 status code
     * @throws {CheckoutResponse502Error} error when the service returns a 502 status code
     * @throws {CheckoutResponse503Error} error when the service returns a 503 status code
     * @throws {CheckoutResponse504Error} error when the service returns a 504 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CheckoutResponse | undefined>;
    /**
     * Create Order Checkout
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface CheckoutResponse400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse400Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse400Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse404Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse404Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse405Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse405Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse405Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse409Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse409Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse409Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse415Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse415Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse415Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse500Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse500Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse502Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse502Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse502Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse503Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse503Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse503Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface CheckoutResponse504Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: CheckoutResponse504Error_errors[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The missingProperties property
     */
    missingProperties?: string[] | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CheckoutResponse504Error_errors extends AdditionalDataHolder, Parsable {
    /**
     * The entity property
     */
    entity?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse400Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse400Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse400Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse400Error}
 */
// @ts-ignore
export function createCheckoutResponse400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse404Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse404Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse404Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse404Error}
 */
// @ts-ignore
export function createCheckoutResponse404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse405Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse405Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse405Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse405Error}
 */
// @ts-ignore
export function createCheckoutResponse405ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse405Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse409Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse409Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse409Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse409Error}
 */
// @ts-ignore
export function createCheckoutResponse409ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse409Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse415Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse415Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse415Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse415Error}
 */
// @ts-ignore
export function createCheckoutResponse415ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse415Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse500Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse500Error}
 */
// @ts-ignore
export function createCheckoutResponse500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse502Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse502Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse502Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse502Error}
 */
// @ts-ignore
export function createCheckoutResponse502ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse502Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse503Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse503Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse503Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse503Error}
 */
// @ts-ignore
export function createCheckoutResponse503ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse503Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse504Error_errors}
 */
// @ts-ignore
export function createCheckoutResponse504Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse504Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckoutResponse504Error}
 */
// @ts-ignore
export function createCheckoutResponse504ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckoutResponse504Error;
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse400Error(checkoutResponse400Error: Partial<CheckoutResponse400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse400Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse400Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse400Error.errors = n.getCollectionOfObjectValues<CheckoutResponse400Error_errors>(createCheckoutResponse400Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse400Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse400Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse400Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse400Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse400Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse400Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse400Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse400Error_errors(checkoutResponse400Error_errors: Partial<CheckoutResponse400Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse400Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse400Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse400Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse404Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse404Error(checkoutResponse404Error: Partial<CheckoutResponse404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse404Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse404Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse404Error.errors = n.getCollectionOfObjectValues<CheckoutResponse404Error_errors>(createCheckoutResponse404Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse404Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse404Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse404Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse404Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse404Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse404Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse404Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse404Error_errors(checkoutResponse404Error_errors: Partial<CheckoutResponse404Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse404Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse404Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse404Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse405Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse405Error(checkoutResponse405Error: Partial<CheckoutResponse405Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse405Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse405Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse405Error.errors = n.getCollectionOfObjectValues<CheckoutResponse405Error_errors>(createCheckoutResponse405Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse405Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse405Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse405Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse405Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse405Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse405Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse405Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse405Error_errors(checkoutResponse405Error_errors: Partial<CheckoutResponse405Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse405Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse405Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse405Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse409Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse409Error(checkoutResponse409Error: Partial<CheckoutResponse409Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse409Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse409Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse409Error.errors = n.getCollectionOfObjectValues<CheckoutResponse409Error_errors>(createCheckoutResponse409Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse409Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse409Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse409Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse409Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse409Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse409Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse409Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse409Error_errors(checkoutResponse409Error_errors: Partial<CheckoutResponse409Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse409Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse409Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse409Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse415Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse415Error(checkoutResponse415Error: Partial<CheckoutResponse415Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse415Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse415Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse415Error.errors = n.getCollectionOfObjectValues<CheckoutResponse415Error_errors>(createCheckoutResponse415Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse415Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse415Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse415Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse415Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse415Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse415Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse415Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse415Error_errors(checkoutResponse415Error_errors: Partial<CheckoutResponse415Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse415Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse415Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse415Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse500Error(checkoutResponse500Error: Partial<CheckoutResponse500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse500Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse500Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse500Error.errors = n.getCollectionOfObjectValues<CheckoutResponse500Error_errors>(createCheckoutResponse500Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse500Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse500Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse500Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse500Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse500Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse500Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse500Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse500Error_errors(checkoutResponse500Error_errors: Partial<CheckoutResponse500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse500Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse500Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse500Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse502Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse502Error(checkoutResponse502Error: Partial<CheckoutResponse502Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse502Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse502Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse502Error.errors = n.getCollectionOfObjectValues<CheckoutResponse502Error_errors>(createCheckoutResponse502Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse502Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse502Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse502Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse502Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse502Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse502Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse502Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse502Error_errors(checkoutResponse502Error_errors: Partial<CheckoutResponse502Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse502Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse502Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse502Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse503Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse503Error(checkoutResponse503Error: Partial<CheckoutResponse503Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse503Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse503Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse503Error.errors = n.getCollectionOfObjectValues<CheckoutResponse503Error_errors>(createCheckoutResponse503Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse503Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse503Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse503Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse503Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse503Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse503Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse503Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse503Error_errors(checkoutResponse503Error_errors: Partial<CheckoutResponse503Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse503Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse503Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse503Error_errors.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse504Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse504Error(checkoutResponse504Error: Partial<CheckoutResponse504Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { checkoutResponse504Error.code = n.getStringValue(); },
        "detail": n => { checkoutResponse504Error.detail = n.getStringValue(); },
        "errors": n => { checkoutResponse504Error.errors = n.getCollectionOfObjectValues<CheckoutResponse504Error_errors>(createCheckoutResponse504Error_errorsFromDiscriminatorValue); },
        "instance": n => { checkoutResponse504Error.instance = n.getStringValue(); },
        "missingProperties": n => { checkoutResponse504Error.missingProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "status": n => { checkoutResponse504Error.status = n.getNumberValue(); },
        "title": n => { checkoutResponse504Error.title = n.getStringValue(); },
        "traceId": n => { checkoutResponse504Error.traceId = n.getStringValue(); },
        "type": n => { checkoutResponse504Error.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @param CheckoutResponse504Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckoutResponse504Error_errors(checkoutResponse504Error_errors: Partial<CheckoutResponse504Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entity": n => { checkoutResponse504Error_errors.entity = n.getStringValue(); },
        "message": n => { checkoutResponse504Error_errors.message = n.getStringValue(); },
        "name": n => { checkoutResponse504Error_errors.name = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param CheckoutResponse400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse400Error(writer: SerializationWriter, checkoutResponse400Error: Partial<CheckoutResponse400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse400Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse400Error.code);
    writer.writeStringValue("detail", checkoutResponse400Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse400Error_errors>("errors", checkoutResponse400Error.errors, serializeCheckoutResponse400Error_errors);
    writer.writeStringValue("instance", checkoutResponse400Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse400Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse400Error.status);
    writer.writeStringValue("title", checkoutResponse400Error.title);
    writer.writeStringValue("traceId", checkoutResponse400Error.traceId);
    writer.writeStringValue("type", checkoutResponse400Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse400Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse400Error_errors(writer: SerializationWriter, checkoutResponse400Error_errors: Partial<CheckoutResponse400Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse400Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse400Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse400Error_errors.message);
    writer.writeStringValue("name", checkoutResponse400Error_errors.name);
    writer.writeAdditionalData(checkoutResponse400Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse404Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse404Error(writer: SerializationWriter, checkoutResponse404Error: Partial<CheckoutResponse404Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse404Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse404Error.code);
    writer.writeStringValue("detail", checkoutResponse404Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse404Error_errors>("errors", checkoutResponse404Error.errors, serializeCheckoutResponse404Error_errors);
    writer.writeStringValue("instance", checkoutResponse404Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse404Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse404Error.status);
    writer.writeStringValue("title", checkoutResponse404Error.title);
    writer.writeStringValue("traceId", checkoutResponse404Error.traceId);
    writer.writeStringValue("type", checkoutResponse404Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse404Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse404Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse404Error_errors(writer: SerializationWriter, checkoutResponse404Error_errors: Partial<CheckoutResponse404Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse404Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse404Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse404Error_errors.message);
    writer.writeStringValue("name", checkoutResponse404Error_errors.name);
    writer.writeAdditionalData(checkoutResponse404Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse405Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse405Error(writer: SerializationWriter, checkoutResponse405Error: Partial<CheckoutResponse405Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse405Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse405Error.code);
    writer.writeStringValue("detail", checkoutResponse405Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse405Error_errors>("errors", checkoutResponse405Error.errors, serializeCheckoutResponse405Error_errors);
    writer.writeStringValue("instance", checkoutResponse405Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse405Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse405Error.status);
    writer.writeStringValue("title", checkoutResponse405Error.title);
    writer.writeStringValue("traceId", checkoutResponse405Error.traceId);
    writer.writeStringValue("type", checkoutResponse405Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse405Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse405Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse405Error_errors(writer: SerializationWriter, checkoutResponse405Error_errors: Partial<CheckoutResponse405Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse405Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse405Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse405Error_errors.message);
    writer.writeStringValue("name", checkoutResponse405Error_errors.name);
    writer.writeAdditionalData(checkoutResponse405Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse409Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse409Error(writer: SerializationWriter, checkoutResponse409Error: Partial<CheckoutResponse409Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse409Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse409Error.code);
    writer.writeStringValue("detail", checkoutResponse409Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse409Error_errors>("errors", checkoutResponse409Error.errors, serializeCheckoutResponse409Error_errors);
    writer.writeStringValue("instance", checkoutResponse409Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse409Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse409Error.status);
    writer.writeStringValue("title", checkoutResponse409Error.title);
    writer.writeStringValue("traceId", checkoutResponse409Error.traceId);
    writer.writeStringValue("type", checkoutResponse409Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse409Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse409Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse409Error_errors(writer: SerializationWriter, checkoutResponse409Error_errors: Partial<CheckoutResponse409Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse409Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse409Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse409Error_errors.message);
    writer.writeStringValue("name", checkoutResponse409Error_errors.name);
    writer.writeAdditionalData(checkoutResponse409Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse415Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse415Error(writer: SerializationWriter, checkoutResponse415Error: Partial<CheckoutResponse415Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse415Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse415Error.code);
    writer.writeStringValue("detail", checkoutResponse415Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse415Error_errors>("errors", checkoutResponse415Error.errors, serializeCheckoutResponse415Error_errors);
    writer.writeStringValue("instance", checkoutResponse415Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse415Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse415Error.status);
    writer.writeStringValue("title", checkoutResponse415Error.title);
    writer.writeStringValue("traceId", checkoutResponse415Error.traceId);
    writer.writeStringValue("type", checkoutResponse415Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse415Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse415Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse415Error_errors(writer: SerializationWriter, checkoutResponse415Error_errors: Partial<CheckoutResponse415Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse415Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse415Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse415Error_errors.message);
    writer.writeStringValue("name", checkoutResponse415Error_errors.name);
    writer.writeAdditionalData(checkoutResponse415Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse500Error(writer: SerializationWriter, checkoutResponse500Error: Partial<CheckoutResponse500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse500Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse500Error.code);
    writer.writeStringValue("detail", checkoutResponse500Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse500Error_errors>("errors", checkoutResponse500Error.errors, serializeCheckoutResponse500Error_errors);
    writer.writeStringValue("instance", checkoutResponse500Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse500Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse500Error.status);
    writer.writeStringValue("title", checkoutResponse500Error.title);
    writer.writeStringValue("traceId", checkoutResponse500Error.traceId);
    writer.writeStringValue("type", checkoutResponse500Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse500Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse500Error_errors(writer: SerializationWriter, checkoutResponse500Error_errors: Partial<CheckoutResponse500Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse500Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse500Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse500Error_errors.message);
    writer.writeStringValue("name", checkoutResponse500Error_errors.name);
    writer.writeAdditionalData(checkoutResponse500Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse502Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse502Error(writer: SerializationWriter, checkoutResponse502Error: Partial<CheckoutResponse502Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse502Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse502Error.code);
    writer.writeStringValue("detail", checkoutResponse502Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse502Error_errors>("errors", checkoutResponse502Error.errors, serializeCheckoutResponse502Error_errors);
    writer.writeStringValue("instance", checkoutResponse502Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse502Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse502Error.status);
    writer.writeStringValue("title", checkoutResponse502Error.title);
    writer.writeStringValue("traceId", checkoutResponse502Error.traceId);
    writer.writeStringValue("type", checkoutResponse502Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse502Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse502Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse502Error_errors(writer: SerializationWriter, checkoutResponse502Error_errors: Partial<CheckoutResponse502Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse502Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse502Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse502Error_errors.message);
    writer.writeStringValue("name", checkoutResponse502Error_errors.name);
    writer.writeAdditionalData(checkoutResponse502Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse503Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse503Error(writer: SerializationWriter, checkoutResponse503Error: Partial<CheckoutResponse503Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse503Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse503Error.code);
    writer.writeStringValue("detail", checkoutResponse503Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse503Error_errors>("errors", checkoutResponse503Error.errors, serializeCheckoutResponse503Error_errors);
    writer.writeStringValue("instance", checkoutResponse503Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse503Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse503Error.status);
    writer.writeStringValue("title", checkoutResponse503Error.title);
    writer.writeStringValue("traceId", checkoutResponse503Error.traceId);
    writer.writeStringValue("type", checkoutResponse503Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse503Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse503Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse503Error_errors(writer: SerializationWriter, checkoutResponse503Error_errors: Partial<CheckoutResponse503Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse503Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse503Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse503Error_errors.message);
    writer.writeStringValue("name", checkoutResponse503Error_errors.name);
    writer.writeAdditionalData(checkoutResponse503Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse504Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse504Error(writer: SerializationWriter, checkoutResponse504Error: Partial<CheckoutResponse504Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse504Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", checkoutResponse504Error.code);
    writer.writeStringValue("detail", checkoutResponse504Error.detail);
    writer.writeCollectionOfObjectValues<CheckoutResponse504Error_errors>("errors", checkoutResponse504Error.errors, serializeCheckoutResponse504Error_errors);
    writer.writeStringValue("instance", checkoutResponse504Error.instance);
    writer.writeCollectionOfPrimitiveValues<string>("missingProperties", checkoutResponse504Error.missingProperties);
    writer.writeNumberValue("status", checkoutResponse504Error.status);
    writer.writeStringValue("title", checkoutResponse504Error.title);
    writer.writeStringValue("traceId", checkoutResponse504Error.traceId);
    writer.writeStringValue("type", checkoutResponse504Error.type ?? "about:blank");
    writer.writeAdditionalData(checkoutResponse504Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CheckoutResponse504Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckoutResponse504Error_errors(writer: SerializationWriter, checkoutResponse504Error_errors: Partial<CheckoutResponse504Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!checkoutResponse504Error_errors || isSerializingDerivedType) { return; }
    writer.writeStringValue("entity", checkoutResponse504Error_errors.entity);
    writer.writeStringValue("message", checkoutResponse504Error_errors.message);
    writer.writeStringValue("name", checkoutResponse504Error_errors.name);
    writer.writeAdditionalData(checkoutResponse504Error_errors.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const CheckoutRequestBuilderUriTemplate = "{+baseurl}/payments/{order_id}/checkout";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckoutRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CheckoutRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCheckoutResponse400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createCheckoutResponse404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            405: createCheckoutResponse405ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createCheckoutResponse409ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            415: createCheckoutResponse415ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createCheckoutResponse500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            502: createCheckoutResponse502ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createCheckoutResponse503ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            504: createCheckoutResponse504ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCheckoutResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
