/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAdminResponseDtoFromDiscriminatorValue, createApiProblemDetailsFromDiscriminatorValue, createConflictProblemDetailsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeAdminResponseDto, serializeCreateAdminRequestDto, type AdminResponseDto, type ApiProblemDetails, type ConflictProblemDetails, type CreateAdminRequestDto, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { ExternalRequestBuilderNavigationMetadata, type ExternalRequestBuilder } from './external/index.js';
// @ts-ignore
import { type WithAdminItemRequestBuilder, WithAdminItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /admins
 */
export interface AdminsRequestBuilder extends BaseRequestBuilder<AdminsRequestBuilder> {
    /**
     * The external property
     */
    get external(): ExternalRequestBuilder;
    /**
     * Gets an item from the ApiSdk.admins.item collection
     * @param adminId Unique identifier of the item
     * @returns {WithAdminItemRequestBuilder}
     */
     byAdminId(adminId: Guid) : WithAdminItemRequestBuilder;
    /**
     * Creates a new administrator workspace account profile.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdminResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ConflictProblemDetails} error when the service returns a 409 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: CreateAdminRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdminResponseDto | undefined>;
    /**
     * Creates a new administrator workspace account profile.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateAdminRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AdminsRequestBuilderUriTemplate = "{+baseurl}/admins";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdminsRequestBuilderNavigationMetadata: Record<Exclude<keyof AdminsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAdminId: {
        requestsMetadata: WithAdminItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["adminId"],
    },
    external: {
        navigationMetadata: ExternalRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AdminsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AdminsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createConflictProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdminResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateAdminRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
