/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createCustomerResponseDtoFromDiscriminatorValue, serializeCustomerResponseDto, serializeUpdateCompanyRequestDto, type ApiProblemDetails, type CustomerResponseDto, type UpdateCompanyRequestDto } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customers/{customer-id}/companies/{companyId}
 */
export interface WithCompanyItemRequestBuilder extends BaseRequestBuilder<WithCompanyItemRequestBuilder> {
    /**
     * Updates company data. Duplicate tax IDs and concurrent customer changes return 409; a customer removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 404 status code
     * @throws {ApiProblemDetails} error when the service returns a 409 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     put(body: UpdateCompanyRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CustomerResponseDto | undefined>;
    /**
     * Updates company data. Duplicate tax IDs and concurrent customer changes return 409; a customer removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateCompanyRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithCompanyItemRequestBuilderUriTemplate = "{+baseurl}/customers/{customer%2Did}/companies/{companyId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithCompanyItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithCompanyItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateCompanyRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
