/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { StripeRequestBuilderRequestsMetadata, type StripeRequestBuilder } from './stripe/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /payments/webhooks
 */
export interface WebhooksRequestBuilder extends BaseRequestBuilder<WebhooksRequestBuilder> {
    /**
     * The stripe property
     */
    get stripe(): StripeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WebhooksRequestBuilderUriTemplate = "{+baseurl}/payments/webhooks";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WebhooksRequestBuilderNavigationMetadata: Record<Exclude<keyof WebhooksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    stripe: {
        requestsMetadata: StripeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
