/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, type ApiProblemDetails } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /favorites/clients/{clientId}/products/{productId}
 */
export interface WithProductItemRequestBuilder extends BaseRequestBuilder<WithProductItemRequestBuilder> {
    /**
     * Removes a specific product from the client's favorites; returns 404 if it is missing when the delete executes.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 404 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Removes a specific product from the client's favorites; returns 404 if it is missing when the delete executes.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithProductItemRequestBuilderUriTemplate = "{+baseurl}/favorites/clients/{clientId}/products/{productId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithProductItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithProductItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
