/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ClientRequestBuilderNavigationMetadata, type ClientRequestBuilder } from './client/index.js';
// @ts-ignore
import { type WithClientItemRequestBuilder, WithClientItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /client-data-versions
 */
export interface ClientDataVersionsRequestBuilder extends BaseRequestBuilder<ClientDataVersionsRequestBuilder> {
    /**
     * The client property
     */
    get client(): ClientRequestBuilder;
    /**
     * Gets an item from the ApiSdk.clientDataVersions.item collection
     * @param clientId Unique identifier of the item
     * @returns {WithClientItemRequestBuilder}
     */
     byClientId(clientId: Guid) : WithClientItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ClientDataVersionsRequestBuilderUriTemplate = "{+baseurl}/client-data-versions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ClientDataVersionsRequestBuilderNavigationMetadata: Record<Exclude<keyof ClientDataVersionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byClientId: {
        requestsMetadata: WithClientItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["clientId"],
    },
    client: {
        navigationMetadata: ClientRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
