/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createCustomerResponseDtoFromDiscriminatorValue, serializeCustomerResponseDto, serializeUpdateIndividualDataRequestDto, type ApiProblemDetails, type CustomerResponseDto, type UpdateIndividualDataRequestDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customers/{customer-id}/individual
 */
export interface IndividualRequestBuilder extends BaseRequestBuilder<IndividualRequestBuilder> {
    /**
     * Updates individual details. A concurrent customer change returns 409; a customer removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ApiProblemDetails} error when the service returns a 404 status code
     * @throws {ApiProblemDetails} error when the service returns a 409 status code
     * @throws {ApiProblemDetails} error when the service returns a 500 status code
     */
     put(body: UpdateIndividualDataRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CustomerResponseDto | undefined>;
    /**
     * Updates individual details. A concurrent customer change returns 409; a customer removed before saving returns 404.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateIndividualDataRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const IndividualRequestBuilderUriTemplate = "{+baseurl}/customers/{customer%2Did}/individual";
/**
 * Metadata for all the requests in the request builder.
 */
export const IndividualRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: IndividualRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateIndividualDataRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
