/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createClientDataVersionResponseDtoFromDiscriminatorValue, createNotFoundProblemDetailsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type ApiProblemDetails, type ClientDataVersionResponseDto, type NotFoundProblemDetails, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /client-data-versions/client/{clientId}
 */
export interface WithClientItemRequestBuilder extends BaseRequestBuilder<WithClientItemRequestBuilder> {
    /**
     * Returns the most recent client data version for the provided client id; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ClientDataVersionResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {NotFoundProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ClientDataVersionResponseDto | undefined>;
    /**
     * Returns the most recent client data version for the provided client id; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithClientItemRequestBuilderUriTemplate = "{+baseurl}/client-data-versions/client/{clientId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithClientItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createNotFoundProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createClientDataVersionResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
