/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createConflictProblemDetailsFromDiscriminatorValue, createCustomerResponseDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCreateCustomerRequestDto, serializeCustomerResponseDto, type ApiProblemDetails, type ConflictProblemDetails, type CreateCustomerRequestDto, type CustomerResponseDto, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { ExternalRequestBuilderNavigationMetadata, type ExternalRequestBuilder } from './external/index.js';
// @ts-ignore
import { CustomerItemRequestBuilderNavigationMetadata, type CustomerItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customers
 */
export interface CustomersRequestBuilder extends BaseRequestBuilder<CustomersRequestBuilder> {
    /**
     * The external property
     */
    get external(): ExternalRequestBuilder;
    /**
     * Gets an item from the ApiSdk.customers.item collection
     * @param customerId Unique identifier of the item
     * @returns {CustomerItemRequestBuilder}
     */
     byCustomerId(customerId: Guid) : CustomerItemRequestBuilder;
    /**
     * Creates a new customer aggregate record complete with individual user data details and optional company metadata.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerResponseDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ConflictProblemDetails} error when the service returns a 409 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: CreateCustomerRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CustomerResponseDto | undefined>;
    /**
     * Creates a new customer aggregate record complete with individual user data details and optional company metadata.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateCustomerRequestDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CustomersRequestBuilderUriTemplate = "{+baseurl}/customers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CustomersRequestBuilderNavigationMetadata: Record<Exclude<keyof CustomersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCustomerId: {
        navigationMetadata: CustomerItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["customer%2Did"],
    },
    external: {
        navigationMetadata: ExternalRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CustomersRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CustomersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createConflictProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateCustomerRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
