/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiProblemDetailsFromDiscriminatorValue, createCurrencyDtoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCurrencyDto, serializeUpdateCurrencyExternalDto, type ApiProblemDetails, type CurrencyDto, type ProblemDetails, type UpdateCurrencyExternalDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /currencies/{id}
 */
export interface CurrenciesItemRequestBuilder extends BaseRequestBuilder<CurrenciesItemRequestBuilder> {
    /**
     * Deletes a currency and returns the deactivated resource.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CurrencyDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CurrencyDto | undefined>;
    /**
     * Updates an existing currency and returns the updated resource.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CurrencyDto>}
     * @throws {ApiProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     put(body: UpdateCurrencyExternalDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CurrencyDto | undefined>;
    /**
     * Deletes a currency and returns the deactivated resource.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates an existing currency and returns the updated resource.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateCurrencyExternalDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CurrenciesItemRequestBuilderUriTemplate = "{+baseurl}/currencies/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CurrenciesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: CurrenciesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCurrencyDtoFromDiscriminatorValue,
    },
    put: {
        uriTemplate: CurrenciesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCurrencyDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateCurrencyExternalDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
