/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNotFoundProblemDetailsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, createShoppingCartResponseDtoFromDiscriminatorValue, type NotFoundProblemDetails, type ProblemDetails, type ShoppingCartResponseDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /shopping-carts/client/{clientId}
 */
export interface WithClientItemRequestBuilder extends BaseRequestBuilder<WithClientItemRequestBuilder> {
    /**
     * Returns the shopping cart assigned to the provided client identifier when it exists; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShoppingCartResponseDto>}
     * @throws {NotFoundProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShoppingCartResponseDto | undefined>;
    /**
     * Returns the shopping cart assigned to the provided client identifier when it exists; 404 otherwise.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithClientItemRequestBuilderUriTemplate = "{+baseurl}/shopping-carts/client/{clientId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithClientItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithClientItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createNotFoundProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createShoppingCartResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
